"""Add concept_ids to LiveSession

Revision ID: 10d882a0ecf0
Revises: 3ecdbcc28128
Create Date: 2026-01-13 16:14:58.304397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d882a0ecf0'
down_revision: Union[str, Sequence[str], None] = '3ecdbcc28128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_sessions', sa.Column('concept_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_sessions', 'concept_ids')
    # ### end Alembic commands ###
