"""Add Google Classroom fields

Revision ID: 1184f91c0623
Revises: 29a5cc166559
Create Date: 2026-01-26 16:26:31.583905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1184f91c0623'
down_revision: Union[str, Sequence[str], None] = '29a5cc166559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('assignments', sa.Column('google_link', sa.String(length=1024), nullable=True))
    op.create_unique_constraint(None, 'assignments', ['google_id'])
    op.add_column('classes', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('classes', sa.Column('is_google_synced', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint(None, 'classes', ['google_id'])
    op.add_column('students', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'students', ['google_id'])
    op.add_column('users', sa.Column('google_refresh_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_refresh_token')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'google_id')
    op.drop_constraint(None, 'classes', type_='unique')
    op.drop_column('classes', 'is_google_synced')
    op.drop_column('classes', 'google_id')
    op.drop_constraint(None, 'assignments', type_='unique')
    op.drop_column('assignments', 'google_link')
    op.drop_column('assignments', 'google_id')
    # ### end Alembic commands ###
