"""Add profile picture url

Revision ID: 29a5cc166559
Revises: 73175a2f777d
Create Date: 2026-01-20 14:53:18.623502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a5cc166559'
down_revision: Union[str, Sequence[str], None] = '73175a2f777d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('profile_picture_url', sa.String(length=1024), nullable=True))
    op.add_column('teachers', sa.Column('profile_picture_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'profile_picture_url')
    op.drop_column('students', 'profile_picture_url')
    # ### end Alembic commands ###
