"""Make UnderstandingScore.assignment_id nullable

Revision ID: 31911b2698a9
Revises: 10d882a0ecf0
Create Date: 2026-01-13 16:15:41.132333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31911b2698a9'
down_revision: Union[str, Sequence[str], None] = '10d882a0ecf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('understanding_scores', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('understanding_scores', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
