"""Add time_spent_seconds to LiveResponse

Revision ID: 3ecdbcc28128
Revises: f85e7184d0a5
Create Date: 2026-01-13 16:11:59.506419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ecdbcc28128'
down_revision: Union[str, Sequence[str], None] = 'f85e7184d0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_responses', sa.Column('time_spent_seconds', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_responses', 'time_spent_seconds')
    # ### end Alembic commands ###
