"""Add level column to assignments

Revision ID: de763400887a
Revises: 7d1c1e4e6c2b
Create Date: 2026-01-09 18:18:26.999555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de763400887a'
down_revision: Union[str, Sequence[str], None] = '7d1c1e4e6c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('level', sa.Integer(), nullable=False, server_default='1'))
    op.drop_index(op.f('ix_understanding_scores_student_assignment'), table_name='understanding_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_understanding_scores_student_assignment'), 'understanding_scores', ['student_id', 'assignment_id'], unique=False)
    op.drop_column('assignments', 'level')
    # ### end Alembic commands ###
